name: BertopicR
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16 
  - pip
  - bertopic=0.15.0
  - numpy=1.24.3
  - pandas=2.0.2
  - scikit-learn=1.2.2
  - pytorch=2.0.0 # Add =cpu* if you only need CPU: pytorch=2.0.0=cpu*
  - sentence-transformers=2.2.2
  - hdbscan=0.8.29
  - umap-learn=0.5.3
  - plotly=5.15.0 # If used directly
  - transformers=4.17.0 # If used directly
  - openai=0.27.8 